# Generated by Django 3.1.3 on 2020-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_userprofile_main_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_id', models.ForeignKey(on_delete=models.SET('player1'), related_name='homes_users_related', to='home.userprofile')),
                ('player2_id', models.ForeignKey(on_delete=models.SET('player2'), related_name='homes_users_related2', to='home.userprofile')),
            ],
        ),
    ]
