# Generated by Django 3.1.3 on 2020-11-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='player1_id',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='player2_id',
            new_name='player2',
        ),
    ]
