# Generated by Django 3.1.3 on 2020-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_auto_20201125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='player1_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player2_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
