# Generated by Django 3.1.3 on 2020-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_auto_20201125_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
