# Generated by Django 3.1.3 on 2020-12-10 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_battle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
