# Generated by Django 3.1.3 on 2020-12-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_auto_20201219_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='max_score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player1_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player2_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
