# Generated by Django 3.1.3 on 2020-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_char',
            field=models.CharField(default='Kazuya', max_length=20),
            preserve_default=False,
        ),
    ]
